{% set name = "napari-aphid" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-aphid-{{ version }}.tar.gz
  sha256: ec0c35e7ed09005cdccddea9f8dd9e0a40f79f712aa86f6ecb0e5f34e8465fa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - h5py
    - imagecodecs
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - pandas
    - python >=3.8,<3.11
    - qtpy
    - scikit-image
    - scikit-learn
    - tifffile
    - tqdm
    - scipy

test:
  imports:
    - napari_aphid
  commands:
    - pip list
    # - pip check  # Wrong dependencies are listed in the original package
  requires:
    - pip

about:
  home: https://github.com/hereariim/napari-aphid
  summary: A plugin to classify aphids by stage of development.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
